name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /travelmakers-tech-blog
      NEXT_PUBLIC_GISCUS_REPO: travelmakers/travelmakers-tech-blog
      NEXT_PUBLIC_GISCUS_REPOSITORY_ID: R_kgDOH3wKpw
      NEXT_PUBLIC_GISCUS_CATEGORY: General
      NEXT_PUBLIC_GISCUS_CATEGORY_ID: DIC_kwDOH3wKp84CRDjl

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn
      - name: Build & Export static files
        run: yarn export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
